### PR TITLE
Update to JD 0.7.1

### PR DESCRIPTION
**Pull request by hotelbrigade**
Please excuse the manual build script and libraries. I don't do Maven!

### CODE REVIEW

**Comment by kwart** [comment]
I've continued in your changes and pushed the branch jd-core-071:
* https://github.com/kwart/jd-cmd/tree/jd-core-071

Could you check it before I'll merge it to master?

**Comment by kwart** [comment]
Modified version of this PR merged in PR #12 . Closing this one.

**Comment by hotelbrigade** [comment]
Looks good! Thanks for your work on this great tool.

**Comment by kwart** [comment]
Thank you for the contribution. It was a great step to move it to 0.7.1.

**Pull request closed without merging**
